// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: protobuf/roomchat.proto

package room_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomChat_RegisterProfile_FullMethodName = "/room_chat.RoomChat/RegisterProfile"
	RoomChat_UpdateProfile_FullMethodName   = "/room_chat.RoomChat/UpdateProfile"
)

// RoomChatClient is the client API for RoomChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomChatClient interface {
	RegisterProfile(ctx context.Context, in *RegisterProfileRequest, opts ...grpc.CallOption) (*RegisterProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*Empty, error)
}

type roomChatClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomChatClient(cc grpc.ClientConnInterface) RoomChatClient {
	return &roomChatClient{cc}
}

func (c *roomChatClient) RegisterProfile(ctx context.Context, in *RegisterProfileRequest, opts ...grpc.CallOption) (*RegisterProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProfileResponse)
	err := c.cc.Invoke(ctx, RoomChat_RegisterProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomChatClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RoomChat_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomChatServer is the server API for RoomChat service.
// All implementations must embed UnimplementedRoomChatServer
// for forward compatibility.
type RoomChatServer interface {
	RegisterProfile(context.Context, *RegisterProfileRequest) (*RegisterProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*Empty, error)
	mustEmbedUnimplementedRoomChatServer()
}

// UnimplementedRoomChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomChatServer struct{}

func (UnimplementedRoomChatServer) RegisterProfile(context.Context, *RegisterProfileRequest) (*RegisterProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProfile not implemented")
}
func (UnimplementedRoomChatServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedRoomChatServer) mustEmbedUnimplementedRoomChatServer() {}
func (UnimplementedRoomChatServer) testEmbeddedByValue()                  {}

// UnsafeRoomChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomChatServer will
// result in compilation errors.
type UnsafeRoomChatServer interface {
	mustEmbedUnimplementedRoomChatServer()
}

func RegisterRoomChatServer(s grpc.ServiceRegistrar, srv RoomChatServer) {
	// If the following call pancis, it indicates UnimplementedRoomChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomChat_ServiceDesc, srv)
}

func _RoomChat_RegisterProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomChatServer).RegisterProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomChat_RegisterProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomChatServer).RegisterProfile(ctx, req.(*RegisterProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomChat_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomChatServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomChat_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomChatServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomChat_ServiceDesc is the grpc.ServiceDesc for RoomChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "room_chat.RoomChat",
	HandlerType: (*RoomChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProfile",
			Handler:    _RoomChat_RegisterProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _RoomChat_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/roomchat.proto",
}
