// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: protobuf/roomchat.proto

package room_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protobuf_roomchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_roomchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_roomchat_proto_rawDescGZIP(), []int{0}
}

type RegisterProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nick          string                 `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProfileRequest) Reset() {
	*x = RegisterProfileRequest{}
	mi := &file_protobuf_roomchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProfileRequest) ProtoMessage() {}

func (x *RegisterProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_roomchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProfileRequest.ProtoReflect.Descriptor instead.
func (*RegisterProfileRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_roomchat_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterProfileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterProfileRequest) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

type RegisterProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProfileResponse) Reset() {
	*x = RegisterProfileResponse{}
	mi := &file_protobuf_roomchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProfileResponse) ProtoMessage() {}

func (x *RegisterProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_roomchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProfileResponse.ProtoReflect.Descriptor instead.
func (*RegisterProfileResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_roomchat_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterProfileResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nick          string                 `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_protobuf_roomchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_roomchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_roomchat_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

var File_protobuf_roomchat_proto protoreflect.FileDescriptor

const file_protobuf_roomchat_proto_rawDesc = "" +
	"\n" +
	"\x17protobuf/roomchat.proto\x12\troom_chat\"\a\n" +
	"\x05Empty\"d\n" +
	"\x16RegisterProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04nick\x18\x03 \x01(\tR\x04nick\")\n" +
	"\x17RegisterProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"*\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04nick\x18\x01 \x01(\tR\x04nick2\xa8\x01\n" +
	"\bRoomChat\x12X\n" +
	"\x0fRegisterProfile\x12!.room_chat.RegisterProfileRequest\x1a\".room_chat.RegisterProfileResponse\x12B\n" +
	"\rUpdateProfile\x12\x1f.room_chat.UpdateProfileRequest\x1a\x10.room_chat.EmptyB\x1fZ\x1dgithub.com/zuczkows/room_chatb\x06proto3"

var (
	file_protobuf_roomchat_proto_rawDescOnce sync.Once
	file_protobuf_roomchat_proto_rawDescData []byte
)

func file_protobuf_roomchat_proto_rawDescGZIP() []byte {
	file_protobuf_roomchat_proto_rawDescOnce.Do(func() {
		file_protobuf_roomchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_roomchat_proto_rawDesc), len(file_protobuf_roomchat_proto_rawDesc)))
	})
	return file_protobuf_roomchat_proto_rawDescData
}

var file_protobuf_roomchat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_roomchat_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: room_chat.Empty
	(*RegisterProfileRequest)(nil),  // 1: room_chat.RegisterProfileRequest
	(*RegisterProfileResponse)(nil), // 2: room_chat.RegisterProfileResponse
	(*UpdateProfileRequest)(nil),    // 3: room_chat.UpdateProfileRequest
}
var file_protobuf_roomchat_proto_depIdxs = []int32{
	1, // 0: room_chat.RoomChat.RegisterProfile:input_type -> room_chat.RegisterProfileRequest
	3, // 1: room_chat.RoomChat.UpdateProfile:input_type -> room_chat.UpdateProfileRequest
	2, // 2: room_chat.RoomChat.RegisterProfile:output_type -> room_chat.RegisterProfileResponse
	0, // 3: room_chat.RoomChat.UpdateProfile:output_type -> room_chat.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_roomchat_proto_init() }
func file_protobuf_roomchat_proto_init() {
	if File_protobuf_roomchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_roomchat_proto_rawDesc), len(file_protobuf_roomchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_roomchat_proto_goTypes,
		DependencyIndexes: file_protobuf_roomchat_proto_depIdxs,
		MessageInfos:      file_protobuf_roomchat_proto_msgTypes,
	}.Build()
	File_protobuf_roomchat_proto = out.File
	file_protobuf_roomchat_proto_goTypes = nil
	file_protobuf_roomchat_proto_depIdxs = nil
}
